### ISSUE TITLE
Is it possible to make the text selectable

### ISSUE THREAD

**Issue by Kamihimmel** [h65wang/flutter-animated-counter#11]
Just like the SelectableText Widget

**Comment by h65wang** [comment]
Each digit is displayed using a separate `Text` widget, so even if we use `SelectableText` widgets, the user will only be able to select a single digit at a time. If you think that'll be useful, please share a user story.

**Comment by h65wang** [comment]
Each digit is displayed using a separate Text widget, so even if we use SelectableText widgets, the user will only be able to select a single digit at a time. If you think that'll be useful, please share a user story. Otherwise, this will probably be a "won't fix".

**Comment by h65wang** [comment]
In the current design, each digit is displayed using a separate `Text` widget (to allow single-digit animation controls), so even if we use `SelectableText` widgets, the user will only be able to select a single digit at a time. If you think that'll be useful, please share a user story. Otherwise, this will probably be a "won't fix".
