### ISSUE TITLE
Only animating last digit

### ISSUE THREAD

**Issue by MilWaxQ** [h65wang/flutter-animated-counter#22]
When I change the value, the widget only animates the last digit of the number, all the other digits just jump to the new value.

**Comment by h65wang** [comment]
Assuming by "other digits" you mean "new digits that did not exist before", for example, if you had `1`, and you add 555 to it, you get new value `556` but did not see animation for the first two "5"s (because those digits did not exist before), then that should be fixed in version 0.3.0 with a new `hideLeadingZeroes` parameter. Please see project examples for code on how to implement that. If that's not what you mean, please reopen this issue.
